2025-03-16 15:26:12,619 [INFO] Configuration chargï¿½e : Config(DATABASE_URL='sqlite:///data.db', DEBUG=True)
2025-03-16 15:26:12,619 [CRITICAL] Erreur critique dï¿½tectï¿½e : division by zero
Traceback (most recent call last):
  File "C:\Users\vincc\Documents\Archilog\src\archilog\__init__.py", line 32, in <module>
    1 / 0  # Division par zï¿½ro volontaire pour gï¿½nï¿½rer une exception
ZeroDivisionError: division by zero
2025-03-16 15:26:12,772 [INFO] BEGIN (implicit)
2025-03-16 15:26:12,772 [INFO] PRAGMA main.table_info("profile")
2025-03-16 15:26:12,772 [INFO] [raw sql] ()
2025-03-16 15:26:12,773 [INFO] COMMIT
2025-03-16 15:26:12,781 [INFO] [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2025-03-16 15:26:12,781 [INFO] [33mPress CTRL+C to quit[0m
2025-03-16 15:26:15,198 [INFO] 127.0.0.1 - - [16/Mar/2025 15:26:15] "GET / HTTP/1.1" 200 -
2025-03-16 15:41:52,017 [INFO] Configuration chargï¿½e : Config(DATABASE_URL='sqlite:///data.db', DEBUG=True)
2025-03-16 15:44:44,192 [INFO] Configuration chargï¿½e : Config(DATABASE_URL='sqlite:///data.db', DEBUG=True)
2025-03-16 15:44:44,350 [INFO] BEGIN (implicit)
2025-03-16 15:44:44,350 [INFO] PRAGMA main.table_info("profile")
2025-03-16 15:44:44,350 [INFO] [raw sql] ()
2025-03-16 15:44:44,351 [INFO] PRAGMA temp.table_info("profile")
2025-03-16 15:44:44,351 [INFO] [raw sql] ()
2025-03-16 15:44:44,351 [INFO] 
CREATE TABLE profile (
	id VARCHAR NOT NULL, 
	name VARCHAR, 
	amount FLOAT, 
	category VARCHAR, 
	PRIMARY KEY (id)
)


2025-03-16 15:44:44,351 [INFO] [no key 0.00008s] ()
2025-03-16 15:44:44,359 [INFO] COMMIT
2025-03-16 15:44:44,367 [INFO] [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2025-03-16 15:44:44,367 [INFO] [33mPress CTRL+C to quit[0m
2025-03-16 15:44:46,974 [INFO] 127.0.0.1 - - [16/Mar/2025 15:44:46] "GET / HTTP/1.1" 200 -
2025-03-16 15:44:53,131 [INFO] 127.0.0.1 - - [16/Mar/2025 15:44:53] "GET /display_create_user HTTP/1.1" 200 -
2025-03-16 15:44:57,028 [INFO] 127.0.0.1 - - [16/Mar/2025 15:44:57] "GET /display_delete_user_page HTTP/1.1" 200 -
2025-03-16 15:45:10,670 [ERROR] Exception on /oeoe [GET]
Traceback (most recent call last):
  File "C:\Users\vincc\Documents\Archilog\.venv\lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\vincc\Documents\Archilog\.venv\lib\site-packages\flask\app.py", line 891, in dispatch_request
    self.raise_routing_exception(req)
  File "C:\Users\vincc\Documents\Archilog\.venv\lib\site-packages\flask\app.py", line 500, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
  File "C:\Users\vincc\Documents\Archilog\.venv\lib\site-packages\flask\ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "C:\Users\vincc\Documents\Archilog\.venv\lib\site-packages\werkzeug\routing\map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\vincc\Documents\Archilog\.venv\lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\vincc\Documents\Archilog\.venv\lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\vincc\Documents\Archilog\.venv\lib\site-packages\flask\app.py", line 802, in handle_user_exception
    return self.handle_http_exception(e)
  File "C:\Users\vincc\Documents\Archilog\.venv\lib\site-packages\flask\app.py", line 777, in handle_http_exception
    return self.ensure_sync(handler)(e)  # type: ignore[no-any-return]
  File "C:\Users\vincc\Documents\Archilog\src\archilog\views\error_handler.py", line 12, in page_not_found
    return render_template("404.html"), 404
  File "C:\Users\vincc\Documents\Archilog\.venv\lib\site-packages\flask\templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "C:\Users\vincc\Documents\Archilog\.venv\lib\site-packages\jinja2\environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Users\vincc\Documents\Archilog\.venv\lib\site-packages\jinja2\environment.py", line 1016, in get_template
    return self._load_template(name, globals)
  File "C:\Users\vincc\Documents\Archilog\.venv\lib\site-packages\jinja2\environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Users\vincc\Documents\Archilog\.venv\lib\site-packages\jinja2\loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "C:\Users\vincc\Documents\Archilog\.venv\lib\site-packages\flask\templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
  File "C:\Users\vincc\Documents\Archilog\.venv\lib\site-packages\flask\templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: 404.html
2025-03-16 15:45:10,673 [INFO] 127.0.0.1 - - [16/Mar/2025 15:45:10] "[35m[1mGET /oeoe HTTP/1.1[0m" 500 -
2025-03-16 15:45:10,738 [ERROR] Error on request:
Traceback (most recent call last):
  File "C:\Users\vincc\Documents\Archilog\.venv\lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\vincc\Documents\Archilog\.venv\lib\site-packages\flask\app.py", line 891, in dispatch_request
    self.raise_routing_exception(req)
  File "C:\Users\vincc\Documents\Archilog\.venv\lib\site-packages\flask\app.py", line 500, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
  File "C:\Users\vincc\Documents\Archilog\.venv\lib\site-packages\flask\ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "C:\Users\vincc\Documents\Archilog\.venv\lib\site-packages\werkzeug\routing\map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\vincc\Documents\Archilog\.venv\lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\vincc\Documents\Archilog\.venv\lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\vincc\Documents\Archilog\.venv\lib\site-packages\flask\app.py", line 802, in handle_user_exception
    return self.handle_http_exception(e)
  File "C:\Users\vincc\Documents\Archilog\.venv\lib\site-packages\flask\app.py", line 777, in handle_http_exception
    return self.ensure_sync(handler)(e)  # type: ignore[no-any-return]
  File "C:\Users\vincc\Documents\Archilog\src\archilog\views\error_handler.py", line 12, in page_not_found
    return render_template("404.html"), 404
  File "C:\Users\vincc\Documents\Archilog\.venv\lib\site-packages\flask\templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "C:\Users\vincc\Documents\Archilog\.venv\lib\site-packages\jinja2\environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Users\vincc\Documents\Archilog\.venv\lib\site-packages\jinja2\environment.py", line 1016, in get_template
    return self._load_template(name, globals)
  File "C:\Users\vincc\Documents\Archilog\.venv\lib\site-packages\jinja2\environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Users\vincc\Documents\Archilog\.venv\lib\site-packages\jinja2\loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "C:\Users\vincc\Documents\Archilog\.venv\lib\site-packages\flask\templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
  File "C:\Users\vincc\Documents\Archilog\.venv\lib\site-packages\flask\templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: 404.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\vincc\Documents\Archilog\.venv\lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\vincc\Documents\Archilog\.venv\lib\site-packages\werkzeug\serving.py", line 331, in execute
    application_iter = app(environ, start_response)
  File "C:\Users\vincc\Documents\Archilog\.venv\lib\site-packages\flask\app.py", line 1536, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\vincc\Documents\Archilog\.venv\lib\site-packages\flask\app.py", line 1514, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\vincc\Documents\Archilog\.venv\lib\site-packages\flask\app.py", line 860, in handle_exception
    server_error = self.ensure_sync(handler)(server_error)
  File "C:\Users\vincc\Documents\Archilog\src\archilog\views\error_handler.py", line 18, in internal_server_error
    return render_template("500.html"), 500
  File "C:\Users\vincc\Documents\Archilog\.venv\lib\site-packages\flask\templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "C:\Users\vincc\Documents\Archilog\.venv\lib\site-packages\jinja2\environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Users\vincc\Documents\Archilog\.venv\lib\site-packages\jinja2\environment.py", line 1016, in get_template
    return self._load_template(name, globals)
  File "C:\Users\vincc\Documents\Archilog\.venv\lib\site-packages\jinja2\environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Users\vincc\Documents\Archilog\.venv\lib\site-packages\jinja2\loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "C:\Users\vincc\Documents\Archilog\.venv\lib\site-packages\flask\templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
  File "C:\Users\vincc\Documents\Archilog\.venv\lib\site-packages\flask\templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: 500.html
2025-03-16 15:45:31,790 [ERROR] Exception on /form [GET]
Traceback (most recent call last):
  File "C:\Users\vincc\Documents\Archilog\.venv\lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\vincc\Documents\Archilog\.venv\lib\site-packages\flask\app.py", line 891, in dispatch_request
    self.raise_routing_exception(req)
  File "C:\Users\vincc\Documents\Archilog\.venv\lib\site-packages\flask\app.py", line 500, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
  File "C:\Users\vincc\Documents\Archilog\.venv\lib\site-packages\flask\ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "C:\Users\vincc\Documents\Archilog\.venv\lib\site-packages\werkzeug\routing\map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\vincc\Documents\Archilog\.venv\lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\vincc\Documents\Archilog\.venv\lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\vincc\Documents\Archilog\.venv\lib\site-packages\flask\app.py", line 802, in handle_user_exception
    return self.handle_http_exception(e)
  File "C:\Users\vincc\Documents\Archilog\.venv\lib\site-packages\flask\app.py", line 777, in handle_http_exception
    return self.ensure_sync(handler)(e)  # type: ignore[no-any-return]
  File "C:\Users\vincc\Documents\Archilog\src\archilog\views\error_handler.py", line 12, in page_not_found
    return render_template("404.html"), 404
  File "C:\Users\vincc\Documents\Archilog\.venv\lib\site-packages\flask\templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "C:\Users\vincc\Documents\Archilog\.venv\lib\site-packages\jinja2\environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Users\vincc\Documents\Archilog\.venv\lib\site-packages\jinja2\environment.py", line 1016, in get_template
    return self._load_template(name, globals)
  File "C:\Users\vincc\Documents\Archilog\.venv\lib\site-packages\jinja2\environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Users\vincc\Documents\Archilog\.venv\lib\site-packages\jinja2\loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "C:\Users\vincc\Documents\Archilog\.venv\lib\site-packages\flask\templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
  File "C:\Users\vincc\Documents\Archilog\.venv\lib\site-packages\flask\templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: 404.html
2025-03-16 15:45:31,793 [INFO] 127.0.0.1 - - [16/Mar/2025 15:45:31] "[35m[1mGET /form HTTP/1.1[0m" 500 -
2025-03-16 15:45:31,795 [ERROR] Error on request:
Traceback (most recent call last):
  File "C:\Users\vincc\Documents\Archilog\.venv\lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\vincc\Documents\Archilog\.venv\lib\site-packages\flask\app.py", line 891, in dispatch_request
    self.raise_routing_exception(req)
  File "C:\Users\vincc\Documents\Archilog\.venv\lib\site-packages\flask\app.py", line 500, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
  File "C:\Users\vincc\Documents\Archilog\.venv\lib\site-packages\flask\ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "C:\Users\vincc\Documents\Archilog\.venv\lib\site-packages\werkzeug\routing\map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\vincc\Documents\Archilog\.venv\lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\vincc\Documents\Archilog\.venv\lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\vincc\Documents\Archilog\.venv\lib\site-packages\flask\app.py", line 802, in handle_user_exception
    return self.handle_http_exception(e)
  File "C:\Users\vincc\Documents\Archilog\.venv\lib\site-packages\flask\app.py", line 777, in handle_http_exception
    return self.ensure_sync(handler)(e)  # type: ignore[no-any-return]
  File "C:\Users\vincc\Documents\Archilog\src\archilog\views\error_handler.py", line 12, in page_not_found
    return render_template("404.html"), 404
  File "C:\Users\vincc\Documents\Archilog\.venv\lib\site-packages\flask\templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "C:\Users\vincc\Documents\Archilog\.venv\lib\site-packages\jinja2\environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Users\vincc\Documents\Archilog\.venv\lib\site-packages\jinja2\environment.py", line 1016, in get_template
    return self._load_template(name, globals)
  File "C:\Users\vincc\Documents\Archilog\.venv\lib\site-packages\jinja2\environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Users\vincc\Documents\Archilog\.venv\lib\site-packages\jinja2\loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "C:\Users\vincc\Documents\Archilog\.venv\lib\site-packages\flask\templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
  File "C:\Users\vincc\Documents\Archilog\.venv\lib\site-packages\flask\templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: 404.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\vincc\Documents\Archilog\.venv\lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\vincc\Documents\Archilog\.venv\lib\site-packages\werkzeug\serving.py", line 331, in execute
    application_iter = app(environ, start_response)
  File "C:\Users\vincc\Documents\Archilog\.venv\lib\site-packages\flask\app.py", line 1536, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\vincc\Documents\Archilog\.venv\lib\site-packages\flask\app.py", line 1514, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\vincc\Documents\Archilog\.venv\lib\site-packages\flask\app.py", line 860, in handle_exception
    server_error = self.ensure_sync(handler)(server_error)
  File "C:\Users\vincc\Documents\Archilog\src\archilog\views\error_handler.py", line 18, in internal_server_error
    return render_template("500.html"), 500
  File "C:\Users\vincc\Documents\Archilog\.venv\lib\site-packages\flask\templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "C:\Users\vincc\Documents\Archilog\.venv\lib\site-packages\jinja2\environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Users\vincc\Documents\Archilog\.venv\lib\site-packages\jinja2\environment.py", line 1016, in get_template
    return self._load_template(name, globals)
  File "C:\Users\vincc\Documents\Archilog\.venv\lib\site-packages\jinja2\environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Users\vincc\Documents\Archilog\.venv\lib\site-packages\jinja2\loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "C:\Users\vincc\Documents\Archilog\.venv\lib\site-packages\flask\templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
  File "C:\Users\vincc\Documents\Archilog\.venv\lib\site-packages\flask\templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: 500.html
2025-03-16 15:45:55,812 [INFO] 127.0.0.1 - - [16/Mar/2025 15:45:55] "[31m[1mGET /delete_user HTTP/1.1[0m" 405 -
2025-03-16 15:49:54,777 [INFO] Configuration chargï¿½e : Config(DATABASE_URL='sqlite:///data.db', DEBUG=True)
2025-03-16 15:49:54,937 [INFO] BEGIN (implicit)
2025-03-16 15:49:54,937 [INFO] PRAGMA main.table_info("profile")
2025-03-16 15:49:54,937 [INFO] [raw sql] ()
2025-03-16 15:49:54,938 [INFO] COMMIT
2025-03-16 15:49:54,945 [INFO] [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2025-03-16 15:49:54,945 [INFO] [33mPress CTRL+C to quit[0m
2025-03-16 15:49:56,680 [INFO] 127.0.0.1 - - [16/Mar/2025 15:49:56] "GET / HTTP/1.1" 200 -
2025-03-16 15:49:57,674 [INFO] 127.0.0.1 - - [16/Mar/2025 15:49:57] "GET /display_create_user HTTP/1.1" 200 -
2025-03-16 15:50:07,513 [ERROR] Exception on /zeuiu [GET]
Traceback (most recent call last):
  File "C:\Users\vincc\Documents\Archilog\.venv\lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\vincc\Documents\Archilog\.venv\lib\site-packages\flask\app.py", line 891, in dispatch_request
    self.raise_routing_exception(req)
  File "C:\Users\vincc\Documents\Archilog\.venv\lib\site-packages\flask\app.py", line 500, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
  File "C:\Users\vincc\Documents\Archilog\.venv\lib\site-packages\flask\ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "C:\Users\vincc\Documents\Archilog\.venv\lib\site-packages\werkzeug\routing\map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\vincc\Documents\Archilog\.venv\lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\vincc\Documents\Archilog\.venv\lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\vincc\Documents\Archilog\.venv\lib\site-packages\flask\app.py", line 802, in handle_user_exception
    return self.handle_http_exception(e)
  File "C:\Users\vincc\Documents\Archilog\.venv\lib\site-packages\flask\app.py", line 777, in handle_http_exception
    return self.ensure_sync(handler)(e)  # type: ignore[no-any-return]
  File "C:\Users\vincc\Documents\Archilog\src\archilog\views\error_handler.py", line 12, in page_not_found
    flash("La page demandï¿½e est introuvable.", "warning")  # Message utilisateur
  File "C:\Users\vincc\Documents\Archilog\.venv\lib\site-packages\flask\helpers.py", line 335, in flash
    session["_flashes"] = flashes
  File "C:\Users\vincc\Documents\Archilog\.venv\lib\site-packages\flask\sessions.py", line 104, in _fail
    raise RuntimeError(
RuntimeError: The session is unavailable because no secret key was set.  Set the secret_key on the application to something unique and secret.
2025-03-16 15:50:07,516 [INFO] 127.0.0.1 - - [16/Mar/2025 15:50:07] "[35m[1mGET /zeuiu HTTP/1.1[0m" 500 -
2025-03-16 15:50:07,529 [ERROR] Error on request:
Traceback (most recent call last):
  File "C:\Users\vincc\Documents\Archilog\.venv\lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\vincc\Documents\Archilog\.venv\lib\site-packages\flask\app.py", line 891, in dispatch_request
    self.raise_routing_exception(req)
  File "C:\Users\vincc\Documents\Archilog\.venv\lib\site-packages\flask\app.py", line 500, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
  File "C:\Users\vincc\Documents\Archilog\.venv\lib\site-packages\flask\ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "C:\Users\vincc\Documents\Archilog\.venv\lib\site-packages\werkzeug\routing\map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\vincc\Documents\Archilog\.venv\lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\vincc\Documents\Archilog\.venv\lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\vincc\Documents\Archilog\.venv\lib\site-packages\flask\app.py", line 802, in handle_user_exception
    return self.handle_http_exception(e)
  File "C:\Users\vincc\Documents\Archilog\.venv\lib\site-packages\flask\app.py", line 777, in handle_http_exception
    return self.ensure_sync(handler)(e)  # type: ignore[no-any-return]
  File "C:\Users\vincc\Documents\Archilog\src\archilog\views\error_handler.py", line 12, in page_not_found
    flash("La page demandï¿½e est introuvable.", "warning")  # Message utilisateur
  File "C:\Users\vincc\Documents\Archilog\.venv\lib\site-packages\flask\helpers.py", line 335, in flash
    session["_flashes"] = flashes
  File "C:\Users\vincc\Documents\Archilog\.venv\lib\site-packages\flask\sessions.py", line 104, in _fail
    raise RuntimeError(
RuntimeError: The session is unavailable because no secret key was set.  Set the secret_key on the application to something unique and secret.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\vincc\Documents\Archilog\.venv\lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\vincc\Documents\Archilog\.venv\lib\site-packages\werkzeug\serving.py", line 331, in execute
    application_iter = app(environ, start_response)
  File "C:\Users\vincc\Documents\Archilog\.venv\lib\site-packages\flask\app.py", line 1536, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\vincc\Documents\Archilog\.venv\lib\site-packages\flask\app.py", line 1514, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\vincc\Documents\Archilog\.venv\lib\site-packages\flask\app.py", line 860, in handle_exception
    server_error = self.ensure_sync(handler)(server_error)
  File "C:\Users\vincc\Documents\Archilog\src\archilog\views\error_handler.py", line 20, in handle_internal_error
    flash("Erreur interne du serveur", "error")  # Message utilisateur
  File "C:\Users\vincc\Documents\Archilog\.venv\lib\site-packages\flask\helpers.py", line 335, in flash
    session["_flashes"] = flashes
  File "C:\Users\vincc\Documents\Archilog\.venv\lib\site-packages\flask\sessions.py", line 104, in _fail
    raise RuntimeError(
RuntimeError: The session is unavailable because no secret key was set.  Set the secret_key on the application to something unique and secret.
2025-03-16 15:54:03,456 [INFO] Configuration chargï¿½e : Config(DATABASE_URL='sqlite:///data.db', DEBUG=True, SECRET_KEY='ma_super_cle_secrete')
2025-03-16 15:54:03,616 [INFO] BEGIN (implicit)
2025-03-16 15:54:03,616 [INFO] PRAGMA main.table_info("profile")
2025-03-16 15:54:03,616 [INFO] [raw sql] ()
2025-03-16 15:54:03,617 [INFO] COMMIT
2025-03-16 15:54:03,624 [INFO] [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2025-03-16 15:54:03,624 [INFO] [33mPress CTRL+C to quit[0m
2025-03-16 15:54:05,765 [INFO] 127.0.0.1 - - [16/Mar/2025 15:54:05] "GET / HTTP/1.1" 200 -
2025-03-16 15:54:10,518 [INFO] 127.0.0.1 - - [16/Mar/2025 15:54:10] "[33mGET /zfzf HTTP/1.1[0m" 404 -
2025-03-16 15:54:14,719 [INFO] 127.0.0.1 - - [16/Mar/2025 15:54:14] "GET / HTTP/1.1" 200 -
2025-03-16 15:54:45,202 [INFO] 127.0.0.1 - - [16/Mar/2025 15:54:45] "[33mGET /zfzf HTTP/1.1[0m" 404 -
2025-03-16 15:54:48,089 [INFO] 127.0.0.1 - - [16/Mar/2025 15:54:48] "[33mGET /zfzfzf HTTP/1.1[0m" 404 -
2025-03-16 15:54:49,343 [INFO] 127.0.0.1 - - [16/Mar/2025 15:54:49] "[33mGET /zfzf HTTP/1.1[0m" 404 -
2025-03-16 15:54:50,218 [INFO] 127.0.0.1 - - [16/Mar/2025 15:54:50] "GET / HTTP/1.1" 200 -
2025-03-16 15:54:51,812 [INFO] 127.0.0.1 - - [16/Mar/2025 15:54:51] "GET /display_delete_user_page HTTP/1.1" 200 -
2025-03-16 15:56:17,188 [INFO] Configuration chargï¿½e : Config(DATABASE_URL='sqlite:///data.db', DEBUG=True, SECRET_KEY='ma_super_cle_secrete')
2025-03-16 15:56:17,353 [INFO] BEGIN (implicit)
2025-03-16 15:56:17,354 [INFO] PRAGMA main.table_info("profile")
2025-03-16 15:56:17,354 [INFO] [raw sql] ()
2025-03-16 15:56:17,354 [INFO] COMMIT
2025-03-16 15:56:17,361 [INFO] [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2025-03-16 15:56:17,361 [INFO] [33mPress CTRL+C to quit[0m
2025-03-16 15:56:20,783 [INFO] 127.0.0.1 - - [16/Mar/2025 15:56:20] "GET / HTTP/1.1" 200 -
2025-03-16 15:56:23,984 [INFO] 127.0.0.1 - - [16/Mar/2025 15:56:23] "GET /display_create_user HTTP/1.1" 200 -
2025-03-16 15:56:26,153 [INFO] 127.0.0.1 - - [16/Mar/2025 15:56:26] "GET /display_delete_user_page HTTP/1.1" 200 -
2025-03-16 15:56:29,422 [INFO] 127.0.0.1 - - [16/Mar/2025 15:56:29] "[33mGET /geg HTTP/1.1[0m" 404 -
2025-03-16 15:56:36,295 [INFO] 127.0.0.1 - - [16/Mar/2025 15:56:36] "GET / HTTP/1.1" 200 -
2025-03-16 15:56:50,869 [INFO] BEGIN (implicit)
2025-03-16 15:56:50,869 [INFO] INSERT INTO profile (id, name, amount, category) VALUES (?, ?, ?, ?)
2025-03-16 15:56:50,869 [INFO] [generated in 0.00032s] ('22079a6a70a041bdadeed8bffcc6f362', 'carret', 500.0, 'zfzf')
2025-03-16 15:56:50,870 [INFO] COMMIT
2025-03-16 15:56:50,880 [INFO] BEGIN (implicit)
2025-03-16 15:56:50,880 [INFO] INSERT INTO profile (id, name, amount, category) VALUES (?, ?, ?, ?)
2025-03-16 15:56:50,880 [INFO] [cached since 0.01129s ago] ('0a81da378cee4f90bd18cb597b21bba9', 'zfzf', 200.0, 'zfzf')
2025-03-16 15:56:50,881 [INFO] COMMIT
2025-03-16 15:56:50,890 [INFO] BEGIN (implicit)
2025-03-16 15:56:50,890 [INFO] INSERT INTO profile (id, name, amount, category) VALUES (?, ?, ?, ?)
2025-03-16 15:56:50,890 [INFO] [cached since 0.02162s ago] ('7979c4081fe24f81bba5817c4a221345', 'cvfzzfvv', 520.0, 'zzfzffzfzf')
2025-03-16 15:56:50,891 [INFO] COMMIT
2025-03-16 15:56:50,901 [INFO] BEGIN (implicit)
2025-03-16 15:56:50,901 [INFO] INSERT INTO profile (id, name, amount, category) VALUES (?, ?, ?, ?)
2025-03-16 15:56:50,901 [INFO] [cached since 0.03268s ago] ('d415df5e20f6446da59d47c84c196dff', 'fgzzfzffzf', 200.0, 'zfzzfzff')
2025-03-16 15:56:50,902 [INFO] COMMIT
2025-03-16 15:56:50,912 [INFO] BEGIN (implicit)
2025-03-16 15:56:50,912 [INFO] INSERT INTO profile (id, name, amount, category) VALUES (?, ?, ?, ?)
2025-03-16 15:56:50,912 [INFO] [cached since 0.04373s ago] ('d96220cc11774eb6ac8b6eb22bf6c667', 'cvvv', 520.0, 'zfzfzf')
2025-03-16 15:56:50,913 [INFO] COMMIT
2025-03-16 15:56:50,922 [INFO] BEGIN (implicit)
2025-03-16 15:56:50,922 [INFO] INSERT INTO profile (id, name, amount, category) VALUES (?, ?, ?, ?)
2025-03-16 15:56:50,923 [INFO] [cached since 0.05395s ago] ('ad0f72a4b5554ea4afa868e853b08412', 'fgzfzf', 200.0, 'zfzf')
2025-03-16 15:56:50,923 [INFO] COMMIT
2025-03-16 15:56:50,933 [INFO] BEGIN (implicit)
2025-03-16 15:56:50,933 [INFO] INSERT INTO profile (id, name, amount, category) VALUES (?, ?, ?, ?)
2025-03-16 15:56:50,933 [INFO] [cached since 0.06435s ago] ('f9b994aa315542baaffd1b20d69b6b8a', 'cvvv', 520.0, 'zfzfzf')
2025-03-16 15:56:50,934 [INFO] COMMIT
2025-03-16 15:56:50,944 [INFO] BEGIN (implicit)
2025-03-16 15:56:50,944 [INFO] INSERT INTO profile (id, name, amount, category) VALUES (?, ?, ?, ?)
2025-03-16 15:56:50,944 [INFO] [cached since 0.07472s ago] ('21151decce3a41b3b1ae4a0200ab0b55', 'wsh', 200.0, 'zfzf')
2025-03-16 15:56:50,944 [INFO] COMMIT
2025-03-16 15:56:50,954 [INFO] BEGIN (implicit)
2025-03-16 15:56:50,954 [INFO] INSERT INTO profile (id, name, amount, category) VALUES (?, ?, ?, ?)
2025-03-16 15:56:50,954 [INFO] [cached since 0.08495s ago] ('6bcbd58850a849c5a8449f8c9ce1976d', 'cvvv', 520.0, 'zfzfzf')
2025-03-16 15:56:50,954 [INFO] COMMIT
2025-03-16 15:56:50,964 [INFO] BEGIN (implicit)
2025-03-16 15:56:50,964 [INFO] INSERT INTO profile (id, name, amount, category) VALUES (?, ?, ?, ?)
2025-03-16 15:56:50,964 [INFO] [cached since 0.09515s ago] ('fe7df3862d8e405ab38971740e14adb2', 'wsh', 200.0, 'zfzf')
2025-03-16 15:56:50,964 [INFO] COMMIT
2025-03-16 15:56:50,974 [INFO] BEGIN (implicit)
2025-03-16 15:56:50,974 [INFO] INSERT INTO profile (id, name, amount, category) VALUES (?, ?, ?, ?)
2025-03-16 15:56:50,974 [INFO] [cached since 0.1057s ago] ('0567ed7937c34134bad89f2c1f9c0fb3', 'fgzfzf', 200.0, 'zfzf')
2025-03-16 15:56:50,975 [INFO] COMMIT
2025-03-16 15:56:50,984 [INFO] BEGIN (implicit)
2025-03-16 15:56:50,985 [INFO] INSERT INTO profile (id, name, amount, category) VALUES (?, ?, ?, ?)
2025-03-16 15:56:50,985 [INFO] [cached since 0.1157s ago] ('447b2af38ecd46f4b3f5ee3518253a9e', 'cvvv', 520.0, 'zfzfzf')
2025-03-16 15:56:50,985 [INFO] COMMIT
2025-03-16 15:56:50,995 [INFO] BEGIN (implicit)
2025-03-16 15:56:50,995 [INFO] INSERT INTO profile (id, name, amount, category) VALUES (?, ?, ?, ?)
2025-03-16 15:56:50,995 [INFO] [cached since 0.1261s ago] ('83a418b6cb2b4eee8f3fb0a2ae2d6f0b', 'wsh', 200.0, 'zfzf')
2025-03-16 15:56:50,996 [INFO] COMMIT
2025-03-16 15:56:51,005 [INFO] BEGIN (implicit)
2025-03-16 15:56:51,005 [INFO] INSERT INTO profile (id, name, amount, category) VALUES (?, ?, ?, ?)
2025-03-16 15:56:51,005 [INFO] [cached since 0.1364s ago] ('f29ce899ebf548b4b0a45cf78f5e9dbe', 'carret', 500.0, 'zfzffz')
2025-03-16 15:56:51,006 [INFO] COMMIT
2025-03-16 15:56:51,015 [INFO] BEGIN (implicit)
2025-03-16 15:56:51,016 [INFO] INSERT INTO profile (id, name, amount, category) VALUES (?, ?, ?, ?)
2025-03-16 15:56:51,016 [INFO] [cached since 0.1467s ago] ('df37113538184348bca7d37696e6c832', 'cvvv', 520.0, 'zfzfzf')
2025-03-16 15:56:51,016 [INFO] COMMIT
2025-03-16 15:56:51,026 [INFO] BEGIN (implicit)
2025-03-16 15:56:51,026 [INFO] INSERT INTO profile (id, name, amount, category) VALUES (?, ?, ?, ?)
2025-03-16 15:56:51,026 [INFO] [cached since 0.1571s ago] ('95c34f34b30e48cdb639ac935a26e65d', 'fgzfzf', 200.0, 'zfzf')
2025-03-16 15:56:51,026 [INFO] COMMIT
2025-03-16 15:56:51,036 [INFO] BEGIN (implicit)
2025-03-16 15:56:51,036 [INFO] INSERT INTO profile (id, name, amount, category) VALUES (?, ?, ?, ?)
2025-03-16 15:56:51,036 [INFO] [cached since 0.1672s ago] ('7f991b67443248f3bdf79772ec7ca54f', 'cvfzzfvv', 520.0, 'zzfzffzfzf')
2025-03-16 15:56:51,037 [INFO] COMMIT
2025-03-16 15:56:51,046 [INFO] BEGIN (implicit)
2025-03-16 15:56:51,046 [INFO] INSERT INTO profile (id, name, amount, category) VALUES (?, ?, ?, ?)
2025-03-16 15:56:51,046 [INFO] [cached since 0.1776s ago] ('a1f15de8945248b5ae1ebc09a1399565', 'fgzzfzffzf', 200.0, 'zfzzfzff')
2025-03-16 15:56:51,047 [INFO] COMMIT
2025-03-16 15:56:51,057 [INFO] BEGIN (implicit)
2025-03-16 15:56:51,057 [INFO] INSERT INTO profile (id, name, amount, category) VALUES (?, ?, ?, ?)
2025-03-16 15:56:51,057 [INFO] [cached since 0.1878s ago] ('918f150165c548cdb34b2a28c0290cff', 'zfzf', 200.0, 'zfzf')
2025-03-16 15:56:51,057 [INFO] COMMIT
2025-03-16 15:56:51,067 [INFO] BEGIN (implicit)
2025-03-16 15:56:51,067 [INFO] INSERT INTO profile (id, name, amount, category) VALUES (?, ?, ?, ?)
2025-03-16 15:56:51,067 [INFO] [cached since 0.1981s ago] ('5150594d9cba487881b4c08342663e08', 'cvfzzfvv', 520.0, 'zzfzffzfzf')
2025-03-16 15:56:51,067 [INFO] COMMIT
2025-03-16 15:56:51,077 [INFO] BEGIN (implicit)
2025-03-16 15:56:51,077 [INFO] INSERT INTO profile (id, name, amount, category) VALUES (?, ?, ?, ?)
2025-03-16 15:56:51,077 [INFO] [cached since 0.2089s ago] ('d5b350295b68415da06e6c0fd4e75836', 'fgzzfzffzf', 200.0, 'zfzzfzff')
2025-03-16 15:56:51,078 [INFO] COMMIT
2025-03-16 15:56:51,087 [INFO] BEGIN (implicit)
2025-03-16 15:56:51,088 [INFO] INSERT INTO profile (id, name, amount, category) VALUES (?, ?, ?, ?)
2025-03-16 15:56:51,088 [INFO] [cached since 0.219s ago] ('b0712aa15cf448c481899fd2777e9160', 'cvvv', 520.0, 'zfzfzf')
2025-03-16 15:56:51,088 [INFO] COMMIT
2025-03-16 15:56:51,098 [INFO] BEGIN (implicit)
2025-03-16 15:56:51,098 [INFO] INSERT INTO profile (id, name, amount, category) VALUES (?, ?, ?, ?)
2025-03-16 15:56:51,098 [INFO] [cached since 0.2292s ago] ('5a4bc697205047a3a16fa725506b6361', 'fgzfzf', 200.0, 'zfzf')
2025-03-16 15:56:51,098 [INFO] COMMIT
2025-03-16 15:56:51,108 [INFO] BEGIN (implicit)
2025-03-16 15:56:51,108 [INFO] INSERT INTO profile (id, name, amount, category) VALUES (?, ?, ?, ?)
2025-03-16 15:56:51,108 [INFO] [cached since 0.2391s ago] ('f33a324303bc46cf995919806b5b6bdc', 'cvvv', 520.0, 'zfzfzf')
2025-03-16 15:56:51,108 [INFO] COMMIT
2025-03-16 15:56:51,118 [INFO] BEGIN (implicit)
2025-03-16 15:56:51,118 [INFO] INSERT INTO profile (id, name, amount, category) VALUES (?, ?, ?, ?)
2025-03-16 15:56:51,118 [INFO] [cached since 0.2493s ago] ('c6fb69ab35314b548e070d35ce014e04', 'wsh', 200.0, 'zfzf')
2025-03-16 15:56:51,119 [INFO] COMMIT
2025-03-16 15:56:51,128 [INFO] BEGIN (implicit)
2025-03-16 15:56:51,128 [INFO] INSERT INTO profile (id, name, amount, category) VALUES (?, ?, ?, ?)
2025-03-16 15:56:51,128 [INFO] [cached since 0.2597s ago] ('67bc765cf5304ca4bb160d4e08d32f0b', 'cvvv', 520.0, 'zfzfzf')
2025-03-16 15:56:51,129 [INFO] COMMIT
2025-03-16 15:56:51,139 [INFO] BEGIN (implicit)
2025-03-16 15:56:51,139 [INFO] INSERT INTO profile (id, name, amount, category) VALUES (?, ?, ?, ?)
2025-03-16 15:56:51,139 [INFO] [cached since 0.2708s ago] ('d30bc98bc7c14edb864f5086f252fb12', 'wsh', 200.0, 'zfzf')
2025-03-16 15:56:51,140 [INFO] COMMIT
2025-03-16 15:56:51,150 [INFO] BEGIN (implicit)
2025-03-16 15:56:51,150 [INFO] INSERT INTO profile (id, name, amount, category) VALUES (?, ?, ?, ?)
2025-03-16 15:56:51,150 [INFO] [cached since 0.2816s ago] ('ed81d98aa00243a79220be7461495d37', 'fgzfzf', 200.0, 'zfzf')
2025-03-16 15:56:51,151 [INFO] COMMIT
2025-03-16 15:56:51,161 [INFO] BEGIN (implicit)
2025-03-16 15:56:51,161 [INFO] INSERT INTO profile (id, name, amount, category) VALUES (?, ?, ?, ?)
2025-03-16 15:56:51,161 [INFO] [cached since 0.2921s ago] ('d1aa572282854388a95b9e36618745fa', 'cvvv', 520.0, 'zfzfzf')
2025-03-16 15:56:51,161 [INFO] COMMIT
2025-03-16 15:56:51,171 [INFO] BEGIN (implicit)
2025-03-16 15:56:51,171 [INFO] INSERT INTO profile (id, name, amount, category) VALUES (?, ?, ?, ?)
2025-03-16 15:56:51,171 [INFO] [cached since 0.3024s ago] ('a81d4fe59fe542a692c079a13ffb839c', 'wsh', 200.0, 'zfzf')
2025-03-16 15:56:51,172 [INFO] COMMIT
2025-03-16 15:56:51,181 [INFO] BEGIN (implicit)
2025-03-16 15:56:51,181 [INFO] INSERT INTO profile (id, name, amount, category) VALUES (?, ?, ?, ?)
2025-03-16 15:56:51,181 [INFO] [cached since 0.3126s ago] ('48ee68772dbe4c49b12ff041b7b93383', 'carret', 500.0, 'zfzffz')
2025-03-16 15:56:51,182 [INFO] COMMIT
2025-03-16 15:56:51,191 [INFO] BEGIN (implicit)
2025-03-16 15:56:51,191 [INFO] INSERT INTO profile (id, name, amount, category) VALUES (?, ?, ?, ?)
2025-03-16 15:56:51,191 [INFO] [cached since 0.3227s ago] ('7a3c536a6a3449b5acf81715f7296393', 'cvvv', 520.0, 'zfzfzf')
2025-03-16 15:56:51,192 [INFO] COMMIT
2025-03-16 15:56:51,204 [INFO] BEGIN (implicit)
2025-03-16 15:56:51,204 [INFO] INSERT INTO profile (id, name, amount, category) VALUES (?, ?, ?, ?)
2025-03-16 15:56:51,204 [INFO] [cached since 0.3354s ago] ('b3d3a8051bbe407cb3e69dd8db41188c', 'fgzfzf', 200.0, 'zfzf')
2025-03-16 15:56:51,205 [INFO] COMMIT
2025-03-16 15:56:51,214 [INFO] BEGIN (implicit)
2025-03-16 15:56:51,214 [INFO] INSERT INTO profile (id, name, amount, category) VALUES (?, ?, ?, ?)
2025-03-16 15:56:51,214 [INFO] [cached since 0.3457s ago] ('3bc7617582094d4fad89574f0cd0506a', 'cvfzzfvv', 520.0, 'zzfzffzfzf')
2025-03-16 15:56:51,215 [INFO] COMMIT
2025-03-16 15:56:51,225 [INFO] BEGIN (implicit)
2025-03-16 15:56:51,225 [INFO] INSERT INTO profile (id, name, amount, category) VALUES (?, ?, ?, ?)
2025-03-16 15:56:51,225 [INFO] [cached since 0.3559s ago] ('fc28c72c69394ddea2199d276db625b0', 'fgzzfzffzf', 200.0, 'zfzzfzff')
2025-03-16 15:56:51,225 [INFO] COMMIT
2025-03-16 15:56:51,235 [INFO] BEGIN (implicit)
2025-03-16 15:56:51,235 [INFO] INSERT INTO profile (id, name, amount, category) VALUES (?, ?, ?, ?)
2025-03-16 15:56:51,235 [INFO] [cached since 0.3662s ago] ('81970ab3ca8948d2a6ad951f7deb77b3', 'zfzf', 200.0, 'zfzf')
2025-03-16 15:56:51,236 [INFO] COMMIT
2025-03-16 15:56:51,245 [INFO] BEGIN (implicit)
2025-03-16 15:56:51,245 [INFO] INSERT INTO profile (id, name, amount, category) VALUES (?, ?, ?, ?)
2025-03-16 15:56:51,246 [INFO] [cached since 0.3769s ago] ('da499b8567be451bae16efa974c4a9fd', 'cvfzzfvv', 520.0, 'zzfzffzfzf')
2025-03-16 15:56:51,246 [INFO] COMMIT
2025-03-16 15:56:51,256 [INFO] BEGIN (implicit)
2025-03-16 15:56:51,256 [INFO] INSERT INTO profile (id, name, amount, category) VALUES (?, ?, ?, ?)
2025-03-16 15:56:51,256 [INFO] [cached since 0.387s ago] ('c9d8bcf8c5b24fbb8d2552d29181a3e7', 'fgzzfzffzf', 200.0, 'zfzzfzff')
2025-03-16 15:56:51,257 [INFO] COMMIT
2025-03-16 15:56:51,266 [INFO] BEGIN (implicit)
2025-03-16 15:56:51,266 [INFO] INSERT INTO profile (id, name, amount, category) VALUES (?, ?, ?, ?)
2025-03-16 15:56:51,266 [INFO] [cached since 0.3976s ago] ('55f35cfda83645b3b735ce0c29017ed0', 'cvvv', 520.0, 'zfzfzf')
2025-03-16 15:56:51,267 [INFO] COMMIT
2025-03-16 15:56:51,279 [INFO] BEGIN (implicit)
2025-03-16 15:56:51,279 [INFO] INSERT INTO profile (id, name, amount, category) VALUES (?, ?, ?, ?)
2025-03-16 15:56:51,279 [INFO] [cached since 0.4102s ago] ('47e0f4822dbc4301b93b6a4cd523d837', 'fgzfzf', 200.0, 'zfzf')
2025-03-16 15:56:51,280 [INFO] COMMIT
2025-03-16 15:56:51,289 [INFO] BEGIN (implicit)
2025-03-16 15:56:51,289 [INFO] INSERT INTO profile (id, name, amount, category) VALUES (?, ?, ?, ?)
2025-03-16 15:56:51,289 [INFO] [cached since 0.4206s ago] ('62d8268c2cfe44a0ba39ae8059fdfecf', 'cvvv', 520.0, 'zfzfzf')
2025-03-16 15:56:51,290 [INFO] COMMIT
2025-03-16 15:56:51,300 [INFO] BEGIN (implicit)
2025-03-16 15:56:51,300 [INFO] INSERT INTO profile (id, name, amount, category) VALUES (?, ?, ?, ?)
2025-03-16 15:56:51,300 [INFO] [cached since 0.4313s ago] ('23b512422b654412a7dbb1888276790d', 'wsh', 200.0, 'zfzf')
2025-03-16 15:56:51,301 [INFO] COMMIT
2025-03-16 15:56:51,310 [INFO] BEGIN (implicit)
2025-03-16 15:56:51,310 [INFO] INSERT INTO profile (id, name, amount, category) VALUES (?, ?, ?, ?)
2025-03-16 15:56:51,310 [INFO] [cached since 0.4416s ago] ('cbbd63a9a9e54c4fa4c4fe4422904013', 'cvvv', 520.0, 'zfzfzf')
2025-03-16 15:56:51,313 [INFO] COMMIT
2025-03-16 15:56:51,333 [INFO] BEGIN (implicit)
2025-03-16 15:56:51,333 [INFO] INSERT INTO profile (id, name, amount, category) VALUES (?, ?, ?, ?)
2025-03-16 15:56:51,334 [INFO] [cached since 0.4648s ago] ('3ff8175e79da4027962e386aa566e363', 'wsh', 200.0, 'zfzf')
2025-03-16 15:56:51,334 [INFO] COMMIT
2025-03-16 15:56:51,344 [INFO] BEGIN (implicit)
2025-03-16 15:56:51,344 [INFO] INSERT INTO profile (id, name, amount, category) VALUES (?, ?, ?, ?)
2025-03-16 15:56:51,344 [INFO] [cached since 0.4751s ago] ('1170e969a33d4d45802a194ee005cf21', 'fgzfzf', 200.0, 'zfzf')
2025-03-16 15:56:51,345 [INFO] COMMIT
2025-03-16 15:56:51,354 [INFO] BEGIN (implicit)
2025-03-16 15:56:51,354 [INFO] INSERT INTO profile (id, name, amount, category) VALUES (?, ?, ?, ?)
2025-03-16 15:56:51,354 [INFO] [cached since 0.4854s ago] ('4a15d0af21c0416fa9a1b213c0dde5c8', 'cvvv', 520.0, 'zfzfzf')
2025-03-16 15:56:51,355 [INFO] COMMIT
2025-03-16 15:56:51,364 [INFO] BEGIN (implicit)
2025-03-16 15:56:51,365 [INFO] INSERT INTO profile (id, name, amount, category) VALUES (?, ?, ?, ?)
2025-03-16 15:56:51,365 [INFO] [cached since 0.496s ago] ('bf4e26dd775e4fe4aa4bf5d39ff64376', 'wsh', 200.0, 'zfzf')
2025-03-16 15:56:51,365 [INFO] COMMIT
2025-03-16 15:56:51,374 [INFO] BEGIN (implicit)
2025-03-16 15:56:51,374 [INFO] INSERT INTO profile (id, name, amount, category) VALUES (?, ?, ?, ?)
2025-03-16 15:56:51,375 [INFO] [cached since 0.5059s ago] ('56258fab825442d09d55bd1677e37fe5', 'carret', 500.0, 'zfzffz')
2025-03-16 15:56:51,375 [INFO] COMMIT
2025-03-16 15:56:51,384 [INFO] BEGIN (implicit)
2025-03-16 15:56:51,384 [INFO] INSERT INTO profile (id, name, amount, category) VALUES (?, ?, ?, ?)
2025-03-16 15:56:51,384 [INFO] [cached since 0.5159s ago] ('80fd704d44a14b2184f95ad1df500e2a', 'cvvv', 520.0, 'zfzfzf')
2025-03-16 15:56:51,385 [INFO] COMMIT
2025-03-16 15:56:51,395 [INFO] BEGIN (implicit)
2025-03-16 15:56:51,395 [INFO] INSERT INTO profile (id, name, amount, category) VALUES (?, ?, ?, ?)
2025-03-16 15:56:51,395 [INFO] [cached since 0.5261s ago] ('903a9a83f55d4a23a05068a2f464ac02', 'fgzfzf', 200.0, 'zfzf')
2025-03-16 15:56:51,395 [INFO] COMMIT
2025-03-16 15:56:51,405 [INFO] BEGIN (implicit)
2025-03-16 15:56:51,405 [INFO] INSERT INTO profile (id, name, amount, category) VALUES (?, ?, ?, ?)
2025-03-16 15:56:51,405 [INFO] [cached since 0.5367s ago] ('3843e070fd604dbba2f541902f9fb94f', 'cvvv', 520.0, 'zfzfzf')
2025-03-16 15:56:51,406 [INFO] COMMIT
2025-03-16 15:56:51,416 [INFO] BEGIN (implicit)
2025-03-16 15:56:51,416 [INFO] INSERT INTO profile (id, name, amount, category) VALUES (?, ?, ?, ?)
2025-03-16 15:56:51,416 [INFO] [cached since 0.5471s ago] ('ee934119c4b54ef58c71c02b05ee6288', 'fgzfzf', 200.0, 'zfzf')
2025-03-16 15:56:51,416 [INFO] COMMIT
2025-03-16 15:56:51,426 [INFO] BEGIN (implicit)
2025-03-16 15:56:51,426 [INFO] INSERT INTO profile (id, name, amount, category) VALUES (?, ?, ?, ?)
2025-03-16 15:56:51,426 [INFO] [cached since 0.5578s ago] ('a52c03a8eec44548a281879fcdcd6dd6', 'cvfzzfvv', 520.0, 'zzfzffzfzf')
2025-03-16 15:56:51,427 [INFO] COMMIT
2025-03-16 15:56:51,437 [INFO] BEGIN (implicit)
2025-03-16 15:56:51,437 [INFO] INSERT INTO profile (id, name, amount, category) VALUES (?, ?, ?, ?)
2025-03-16 15:56:51,437 [INFO] [cached since 0.5682s ago] ('6361f45ab8b645ef98ec85e437a329f8', 'fgzzfzffzf', 200.0, 'zfzzfzff')
2025-03-16 15:56:51,437 [INFO] COMMIT
2025-03-16 15:56:51,447 [INFO] BEGIN (implicit)
2025-03-16 15:56:51,447 [INFO] INSERT INTO profile (id, name, amount, category) VALUES (?, ?, ?, ?)
2025-03-16 15:56:51,447 [INFO] [cached since 0.5785s ago] ('e1a7ecaba2d64d1297a74ea935a0c6f4', 'zfzf', 200.0, 'zfzf')
2025-03-16 15:56:51,448 [INFO] COMMIT
2025-03-16 15:56:51,457 [INFO] BEGIN (implicit)
2025-03-16 15:56:51,457 [INFO] INSERT INTO profile (id, name, amount, category) VALUES (?, ?, ?, ?)
2025-03-16 15:56:51,457 [INFO] [cached since 0.5889s ago] ('8a2040008e3c4c8880ef678fc385c44a', 'cvfzzfvv', 520.0, 'zzfzffzfzf')
2025-03-16 15:56:51,458 [INFO] COMMIT
2025-03-16 15:56:51,468 [INFO] BEGIN (implicit)
2025-03-16 15:56:51,468 [INFO] INSERT INTO profile (id, name, amount, category) VALUES (?, ?, ?, ?)
2025-03-16 15:56:51,468 [INFO] [cached since 0.5996s ago] ('8d5c759b12ce42438b16ee3f42afb6d7', 'fgzzfzffzf', 200.0, 'zfzzfzff')
2025-03-16 15:56:51,469 [INFO] COMMIT
2025-03-16 15:56:51,479 [INFO] BEGIN (implicit)
2025-03-16 15:56:51,479 [INFO] INSERT INTO profile (id, name, amount, category) VALUES (?, ?, ?, ?)
2025-03-16 15:56:51,479 [INFO] [cached since 0.6102s ago] ('7fb62c654feb43a08e0f0a5e8c2838e4', 'cvvv', 520.0, 'zfzfzf')
2025-03-16 15:56:51,479 [INFO] COMMIT
2025-03-16 15:56:51,489 [INFO] BEGIN (implicit)
2025-03-16 15:56:51,489 [INFO] INSERT INTO profile (id, name, amount, category) VALUES (?, ?, ?, ?)
2025-03-16 15:56:51,489 [INFO] [cached since 0.6208s ago] ('e7625d94b00247958ac884a21fd2b096', 'fgzfzf', 200.0, 'zfzf')
2025-03-16 15:56:51,490 [INFO] COMMIT
2025-03-16 15:56:51,499 [INFO] BEGIN (implicit)
2025-03-16 15:56:51,500 [INFO] INSERT INTO profile (id, name, amount, category) VALUES (?, ?, ?, ?)
2025-03-16 15:56:51,500 [INFO] [cached since 0.631s ago] ('b130f6a79ff24c3eb0d3fff5e3bec86d', 'cvvv', 520.0, 'zfzfzf')
2025-03-16 15:56:51,500 [INFO] COMMIT
2025-03-16 15:56:51,510 [INFO] BEGIN (implicit)
2025-03-16 15:56:51,510 [INFO] INSERT INTO profile (id, name, amount, category) VALUES (?, ?, ?, ?)
2025-03-16 15:56:51,510 [INFO] [cached since 0.6414s ago] ('cdd3644f3468489bac2c995bde0376f3', 'wsh', 200.0, 'zfzf')
2025-03-16 15:56:51,511 [INFO] COMMIT
2025-03-16 15:56:51,520 [INFO] BEGIN (implicit)
2025-03-16 15:56:51,520 [INFO] INSERT INTO profile (id, name, amount, category) VALUES (?, ?, ?, ?)
2025-03-16 15:56:51,520 [INFO] [cached since 0.6517s ago] ('773affa2e09e4cf68b44d2528d6dee68', 'cvvv', 520.0, 'zfzfzf')
2025-03-16 15:56:51,521 [INFO] COMMIT
2025-03-16 15:56:51,531 [INFO] BEGIN (implicit)
2025-03-16 15:56:51,531 [INFO] INSERT INTO profile (id, name, amount, category) VALUES (?, ?, ?, ?)
2025-03-16 15:56:51,531 [INFO] [cached since 0.6621s ago] ('8e09041571284218bf94cced848281fb', 'wsh', 200.0, 'zfzf')
2025-03-16 15:56:51,531 [INFO] COMMIT
2025-03-16 15:56:51,541 [INFO] BEGIN (implicit)
2025-03-16 15:56:51,541 [INFO] INSERT INTO profile (id, name, amount, category) VALUES (?, ?, ?, ?)
2025-03-16 15:56:51,541 [INFO] [cached since 0.6725s ago] ('6b8de1f01f6b44c6bac2643f2c872343', 'fgzfzf', 200.0, 'zfzf')
2025-03-16 15:56:51,542 [INFO] COMMIT
2025-03-16 15:56:51,551 [INFO] BEGIN (implicit)
2025-03-16 15:56:51,551 [INFO] INSERT INTO profile (id, name, amount, category) VALUES (?, ?, ?, ?)
2025-03-16 15:56:51,551 [INFO] [cached since 0.6824s ago] ('91a95b7593a6452a84c4e9adced96e00', 'cvvv', 520.0, 'zfzfzf')
2025-03-16 15:56:51,552 [INFO] COMMIT
2025-03-16 15:56:51,561 [INFO] BEGIN (implicit)
2025-03-16 15:56:51,562 [INFO] INSERT INTO profile (id, name, amount, category) VALUES (?, ?, ?, ?)
2025-03-16 15:56:51,562 [INFO] [cached since 0.6926s ago] ('5c29f8b05e1d415db46317f07844e85e', 'wsh', 200.0, 'zfzf')
2025-03-16 15:56:51,562 [INFO] COMMIT
2025-03-16 15:56:51,571 [INFO] BEGIN (implicit)
2025-03-16 15:56:51,572 [INFO] INSERT INTO profile (id, name, amount, category) VALUES (?, ?, ?, ?)
2025-03-16 15:56:51,572 [INFO] [cached since 0.7028s ago] ('741797266f5342d3b8518a679c4aa344', 'carret', 500.0, 'zfzffz')
2025-03-16 15:56:51,572 [INFO] COMMIT
2025-03-16 15:56:51,583 [INFO] BEGIN (implicit)
2025-03-16 15:56:51,583 [INFO] INSERT INTO profile (id, name, amount, category) VALUES (?, ?, ?, ?)
2025-03-16 15:56:51,583 [INFO] [cached since 0.7139s ago] ('8c316a46b10344819afae8c5c911bca4', 'cvvv', 520.0, 'zfzfzf')
2025-03-16 15:56:51,583 [INFO] COMMIT
2025-03-16 15:56:51,593 [INFO] BEGIN (implicit)
2025-03-16 15:56:51,593 [INFO] INSERT INTO profile (id, name, amount, category) VALUES (?, ?, ?, ?)
2025-03-16 15:56:51,593 [INFO] [cached since 0.724s ago] ('5bca34b9e45946619344dacf8c465808', 'fgzfzf', 200.0, 'zfzf')
2025-03-16 15:56:51,594 [INFO] COMMIT
2025-03-16 15:56:51,603 [INFO] BEGIN (implicit)
2025-03-16 15:56:51,603 [INFO] INSERT INTO profile (id, name, amount, category) VALUES (?, ?, ?, ?)
2025-03-16 15:56:51,603 [INFO] [cached since 0.7345s ago] ('f7220f49dd7f40b198696469cfabcb4e', 'cvvv', 520.0, 'zfzfzf')
2025-03-16 15:56:51,604 [INFO] COMMIT
2025-03-16 15:56:51,613 [INFO] BEGIN (implicit)
2025-03-16 15:56:51,614 [INFO] INSERT INTO profile (id, name, amount, category) VALUES (?, ?, ?, ?)
2025-03-16 15:56:51,614 [INFO] [cached since 0.7446s ago] ('4f629faa8c26487eb785f1d4cc7e21a3', 'wsh', 200.0, 'zfzf')
2025-03-16 15:56:51,614 [INFO] COMMIT
2025-03-16 15:56:51,623 [INFO] 127.0.0.1 - - [16/Mar/2025 15:56:51] "POST /import_csv HTTP/1.1" 200 -
2025-03-16 15:57:02,590 [INFO] 127.0.0.1 - - [16/Mar/2025 15:57:02] "GET / HTTP/1.1" 200 -
